# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dydra-py',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/dydra-py',
                'lib_path': 'dydra_py'},
  'syms': { 'dydra_py.api': { 'dydra_py.api.DydraClient': ('api.html#dydraclient', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.__init__': ('api.html#dydraclient.__init__', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.clear': ('api.html#dydraclient.clear', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.import_by_file': ('api.html#dydraclient.import_by_file', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.load_env': ('api.html#dydraclient.load_env', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.query': ('api.html#dydraclient.query', 'dydra_py/api.py')},
            'dydra_py.core': { 'dydra_py.core.DydraClient': ('core.html#dydraclient', 'dydra_py/core.py'),
                               'dydra_py.core.DydraClient.__init__': ('core.html#dydraclient.__init__', 'dydra_py/core.py'),
                               'dydra_py.core.DydraClient.clear': ('core.html#dydraclient.clear', 'dydra_py/core.py'),
                               'dydra_py.core.DydraClient.import_by_file': ('core.html#dydraclient.import_by_file', 'dydra_py/core.py'),
                               'dydra_py.core.DydraClient.load_env': ('core.html#dydraclient.load_env', 'dydra_py/core.py'),
                               'dydra_py.core.DydraClient.query': ('core.html#dydraclient.query', 'dydra_py/core.py')}}}
