# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dydra-py',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/dydra-py',
                'lib_path': 'dydra_py'},
  'syms': { 'dydra_py.api': { 'dydra_py.api.DydraClient': ('api.html#dydraclient', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.__init__': ('api.html#dydraclient.__init__', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient._chunk_rdf_file': ('api.html#dydraclient._chunk_rdf_file', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient._clear_output_dir': ('api.html#dydraclient._clear_output_dir', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient._serialize_chunk': ('api.html#dydraclient._serialize_chunk', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.clear': ('api.html#dydraclient.clear', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.delete_by_file': ('api.html#dydraclient.delete_by_file', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.delete_by_subjects': ('api.html#dydraclient.delete_by_subjects', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.import_by_file': ('api.html#dydraclient.import_by_file', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.load_env': ('api.html#dydraclient.load_env', 'dydra_py/api.py'),
                              'dydra_py.api.DydraClient.query': ('api.html#dydraclient.query', 'dydra_py/api.py')}}}
